# Generated by Django 3.1.5 on 2021-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_auto_20210610_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
